sudo: required
services:
    - docker
#
#before_install:
#    - docker build -t phuongphh/react-test -f ./client/Dockerfile.dev ./client

#script:
#    - docker run -e CI=true phuongphh/react-test npm test

#after_success:
script:
    - docker build -t phuongphh/multi-client ./client
    - docker build -t phuongphh/multi-nginx ./nginx
    - docker build -t phuongphh/multi-server ./server
    - docker build -t phuongphh/multi-worker ./worker
    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take all those images and push to docker hub
    - docker push phuongphh/multi-client 
    - docker push phuongphh/multi-nginx
    - docker push phuongphh/multi-server
    - docker push phuongphh/multi-worker